#ifndef SCC_KV_FFI_H
#define SCC_KV_FFI_H

/* This file was auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct SccKvStore SccKvStore;

/**
 * Listener callback: `key == NULL` means "everything changed" (clear);
 * otherwise `key`/`key_len` is the UTF-8 key, not NUL-terminated.
 */
typedef void (*SccKvListener)(void *user_data, const uint8_t *key, uintptr_t key_len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Applies a transaction batch atomically as one WAL record (all-or-nothing on
 * replay). `ptr`/`len` is the packed buffer `[u32 count]` + ops.
 */
int32_t scc_kv_apply_batch(struct SccKvStore *handle, const uint8_t *ptr, uintptr_t len);

/**
 * Opens (or returns the already-open) persistent store `id` under `dir`.
 * A non-empty `enc_key` passphrase enables encryption at rest (the 32-byte
 * cipher key is derived via SHA-256). Returns NULL on error.
 */
struct SccKvStore *scc_kv_open(const char *dir,
                               const char *id,
                               bool strict,
                               bool recreate,
                               const uint8_t *enc_key,
                               uintptr_t enc_key_len,
                               uintptr_t max_entries,
                               uint64_t ttl_sweep_interval_ms);

/**
 * Returns the named in-memory store, creating it on first use. NULL on error.
 */
struct SccKvStore *scc_kv_in_memory(const char *id,
                                    uintptr_t max_entries,
                                    uint64_t ttl_sweep_interval_ms);

/**
 * Closes the underlying store and removes it from the registry. 0 ok, -1 error.
 * The handle itself must still be released with `scc_kv_release`.
 */
int32_t scc_kv_close(struct SccKvStore *h);

/**
 * Frees the handle. The store stays registered (reopen returns it) unless
 * `scc_kv_close` was called first.
 */
void scc_kv_release(struct SccKvStore *h);

/**
 * Sets `key` to the value encoded as (tag, data, len). 0 ok, -1 error.
 */
int32_t scc_kv_set(struct SccKvStore *h,
                   const uint8_t *key,
                   uintptr_t key_len,
                   uint8_t tag,
                   const uint8_t *data,
                   uintptr_t len);

/**
 * Reads `key`. 1 found (out params set, buffer freed via `scc_kv_free`),
 * 0 missing, -1 error.
 */
int32_t scc_kv_get(struct SccKvStore *h,
                   const uint8_t *key,
                   uintptr_t key_len,
                   uint8_t *out_tag,
                   uint8_t **out_data,
                   uintptr_t *out_len);

/**
 * 1 if `key` exists, 0 if not, -1 on error.
 */
int32_t scc_kv_contains(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len);

/**
 * 1 removed, 0 missing, -1 error.
 */
int32_t scc_kv_remove(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len);

/**
 * All keys packed as repeated `[u32 len LE][utf8 bytes]`. Empty store:
 * NULL with *out_len = 0. Error: NULL with *out_len = 1.
 */
uint8_t *scc_kv_keys(struct SccKvStore *h, uintptr_t *out_len);

/**
 * 0 ok, -1 error.
 */
int32_t scc_kv_clear(struct SccKvStore *h);

/**
 * Durability barrier: blocks until the WAL is drained and fsynced. 0 ok, -1 error.
 */
int32_t scc_kv_flush(struct SccKvStore *h);

/**
 * Number of keys. 0 on a null handle (with error set).
 */
uint64_t scc_kv_len(struct SccKvStore *h);

/**
 * Fast-path string/bytes/json read into a caller-provided buffer, avoiding
 * heap allocation. Returns 1 found (with `*out_len` set; bytes are copied
 * only when `*out_len <= cap` — otherwise call again with a larger buffer),
 * 0 missing or type mismatch, -1 error.
 */
int32_t scc_kv_get_raw(struct SccKvStore *h,
                       const uint8_t *key,
                       uintptr_t key_len,
                       uint8_t expected_tag,
                       uint8_t *buf,
                       uintptr_t cap,
                       uintptr_t *out_len);

/**
 * Zero-allocation number read. 1 found, 0 missing/type mismatch, -1 error.
 */
int32_t scc_kv_get_f64(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len, double *out);

/**
 * Zero-allocation boolean read. 1 found, 0 missing/type mismatch, -1 error.
 */
int32_t scc_kv_get_bool(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len, bool *out);

/**
 * Sets `key` with a TTL: the entry expires `ttl_ms` from now. 0 ok, -1 error.
 */
int32_t scc_kv_set_ttl(struct SccKvStore *h,
                       const uint8_t *key,
                       uintptr_t key_len,
                       uint8_t tag,
                       const uint8_t *data,
                       uintptr_t len,
                       uint64_t ttl_ms);

/**
 * Fast-path string set: no tag round trip, no UTF-8 scan. 0 ok, -1 error.
 */
int32_t scc_kv_set_str(struct SccKvStore *h,
                       const uint8_t *key,
                       uintptr_t key_len,
                       const uint8_t *data,
                       uintptr_t len);

/**
 * Fast-path number set. 0 ok, -1 error.
 */
int32_t scc_kv_set_f64(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len, double value);

/**
 * Fast-path boolean set. 0 ok, -1 error.
 */
int32_t scc_kv_set_bool(struct SccKvStore *h, const uint8_t *key, uintptr_t key_len, bool value);

/**
 * Batch string set. `data` holds `count` packed entries, each
 * `[u32 key_len LE][key][u32 val_len LE][val]`. All records land in a single
 * WAL append; a malformed buffer applies nothing. 0 ok, -1 error.
 */
int32_t scc_kv_set_many_str(struct SccKvStore *h,
                            const uint8_t *data,
                            uintptr_t len,
                            uintptr_t count);

/**
 * Subscribes to change events. Returns a listener id (> 0), or 0 on error.
 */
uint64_t scc_kv_subscribe(struct SccKvStore *h, SccKvListener cb, void *user_data);

/**
 * 1 removed, 0 unknown id, -1 error.
 */
int32_t scc_kv_unsubscribe(struct SccKvStore *h, uint64_t id);

/**
 * Frees a buffer returned by `scc_kv_get` / `scc_kv_keys`.
 */
void scc_kv_free(uint8_t *ptr, uintptr_t len);

/**
 * Returns the last error on this thread as a heap CString, or NULL.
 * Caller frees with `scc_kv_free_cstring`.
 */
char *scc_kv_last_error(void);

/**
 * Frees a string returned by `scc_kv_last_error`.
 */
void scc_kv_free_cstring(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCC_KV_FFI_H */
